project:
  type: website
  output-dir: docs
  execute-dir: project

website: 
  title: "下層植生の解析"
  description: "Analysis of understory vegetation using R and Quarto"
  navbar: 
    left:
      - href: index.qmd
        text: "Home"
      - href: notebooks/classify_quadrat_regions_explained.qmd
        text: "下層植生の分類方法について"
      - href: notebooks/hsv_color_space.qmd
        text: "HSV色空間について"
      - href: notebooks/projective_transformation.qmd
        text: "射影変換について"
    tools:
      - icon: "github"
        href: "https://github.com/maple60/understory-cover-analysis"
  repo-url: "https://github.com/maple60/understory-cover-analysis"
  repo-actions: [edit, source, issue]

format:
  html:
    toc: true
    theme: cosmo

bibliography: references.bib